return {
  ["workshop-1171138081"]={ configuration_options={  }, enabled=true },
  ["workshop-1204112832"]={ configuration_options={ language=2 }, enabled=true },
  ["workshop-1301033176"]={ configuration_options={ LANG="simplified" }, enabled=true },
  ["workshop-347079953"]={
    configuration_options={ DFV_Language="CN", DFV_MinimalMode="default" },
    enabled=true 
  },
  ["workshop-356420397"]={ configuration_options={  }, enabled=true },
  ["workshop-356435289"]={ configuration_options={ fishfarmrecipe="easy" }, enabled=true },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-374550642"]={ configuration_options={ MAXSTACKSIZE=99 }, enabled=true },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-381565292"]={
    configuration_options={
      waiter_cookableblubber="0",
      waiter_cookablepetals="1",
      waiter_cookableplantmeat="1",
      waiter_cookableseeds="1",
      waiter_cookablewings="1",
      waiter_cookablewobster="0",
      waiter_crops="1",
      waiter_frozen="1",
      waiter_garleekdrop="1",
      waiter_meatdrop=3,
      waiter_mushrooms="1",
      waiter_rutabeeta=1,
      waiter_treedrop=1,
      waiter_vineydrop="0" 
    },
    enabled=true 
  },
  ["workshop-382177939"]={
    configuration_options={ [""]=true, eightxten="5x16", workit="nope" },
    enabled=true 
  },
  ["workshop-385006082"]={
    configuration_options={ [""]=0, FueledLights="no", light_color="color4", path_lightrecipe="easy" },
    enabled=true 
  },
  ["workshop-396822875"]={ configuration_options={ OPT_DIFFICULTY=0 }, enabled=true },
  ["workshop-418604101"]={ configuration_options={  }, enabled=true },
  ["workshop-444235588"]={
    configuration_options={
      deluxeEndoFirepitBurnRate=0.25,
      deluxeFirepitBurnRate=0.25,
      dropLoot="yes",
      endoDropLoot="yes",
      heatStarBurnRate=1.5,
      heatStarDropLoot="yes",
      iceStarBurnRate=1.5,
      iceStarDropLoot="yes",
      recipeCost="cheap",
      starsSpawnHounds="no" 
    },
    enabled=true 
  },
  ["workshop-447092740"]={ configuration_options={  }, enabled=true },
  ["workshop-458587300"]={ configuration_options={ Ownership=false, Travel_Cost=128 }, enabled=true },
  ["workshop-462372013"]={ configuration_options={  }, enabled=true },
  ["workshop-462434129"]={
    configuration_options={
      MOD_RESTART_ALLOW_KILL=true,
      MOD_RESTART_ALLOW_RESTART=true,
      MOD_RESTART_ALLOW_RESURRECT=true,
      MOD_RESTART_CD_BONUS=0,
      MOD_RESTART_CD_KILL=0,
      MOD_RESTART_CD_MAX=0,
      MOD_RESTART_CD_RESTART=0,
      MOD_RESTART_CD_RESURRECT=0,
      MOD_RESTART_FORCE_DROP_MODE=2,
      MOD_RESTART_IGNORING_ADMIN=true,
      MOD_RESTART_MAP_SAVE=1,
      MOD_RESTART_RESURRECT_HEALTH=100,
      MOD_RESTART_TRIGGER_MODE=1,
      MOD_RESTART_WELCOME_TIPS=true,
      MOD_RESTART_WELCOME_TIPS_TIME=5 
    },
    enabled=true 
  },
  ["workshop-512502326"]={ configuration_options={ MAXPETALS=8, PETALSPERDAY=4 }, enabled=true },
  ["workshop-514078314"]={
    configuration_options={
      EnableFlooringPlanting=false,
      EnableGameTurfRecipes=1,
      EnableIndividualization=true,
      EnableNonPlayerSpeed=false,
      EnableTurfedTurfRecipes=1,
      InsulatingTurfs=1,
      InsulationDuration=480,
      RainProtectingTurfs=1,
      SanityTurfs=1,
      SpeedyTurfSpeeds=1.5,
      SpeedyTurfs=1 
    },
    enabled=true 
  },
  ["workshop-554999204"]={ configuration_options={  }, enabled=true },
  ["workshop-572538624"]={
    configuration_options={
      IS_CHS_ALL_MOD=true,
      IS_CHS_CHARACTER=true,
      IS_CHS_FIX_ALL=true,
      IS_CHS_SETTINGS=true 
    },
    enabled=true 
  },
  ["workshop-587832350"]={ configuration_options={ craft="easy" }, enabled=true },
  ["workshop-604761020"]={
    configuration_options={
      RUOYINXIAN=false,
      SHENGDANSHI=false,
      baoshibaolv=2,
      blue_baoshi=1,
      er_shuoming=0,
      green_baoshi=1,
      huangjinbaolv=2,
      marble_suipian=1,
      orange_baoshi=1,
      purple_baoshi=1,
      red_baoshi=1,
      shishengzhang=0,
      shitoubaolv=2,
      thulecite_xiukuang=1,
      wajuecishu=1,
      yellow_baoshi=1,
      yi_shuoming=0 
    },
    enabled=true 
  },
  ["workshop-661253977"]={
    configuration_options={ amudiao=true, baodiao=0, kong=0, rendiao=0, zbdiao=true },
    enabled=true 
  },
  ["workshop-663554209"]={
    configuration_options={
      Craft="Easy",
      Destroyable="yees",
      Position="Center",
      Slots=80,
      chilltime=0,
      lightradius=10 
    },
    enabled=true 
  },
  ["workshop-666155465"]={
    configuration_options={ food_estimation=1, food_order=1, food_style=1, lang="chs", show_food_units=1 },
    enabled=true 
  },
  ["workshop-714712361"]={
    configuration_options={
      ANNOUNCE_TIP=true,
      PACKS_BACKPACK=0,
      PACKS_BUFF=2,
      PACKS_BUILD=10,
      PACKS_CD=10,
      PACKS_CHARACTER=3,
      PACKS_SCIENCE=1,
      PACKS_SEASON=true,
      RESOURCE_BALANCE=true,
      acorn=0,
      amulet=0,
      armorwood=1,
      axe=1,
      bandage=2,
      cane=1,
      compass=0,
      cutgrass=5,
      cutreeds=0,
      dragonpie=2,
      flint=3,
      footballhat=1,
      gears=0,
      goldnugget=0,
      heatrock=1,
      ice=0,
      log=5,
      meat_dried=4,
      nitre=0,
      pickaxe=1,
      pigskin=0,
      poop=0,
      rocks=3,
      shovel=1,
      silk=0,
      spear=1,
      torch=5,
      twigs=5,
      umbrella=1 
    },
    enabled=true 
  },
  ["workshop-785295023"]={
    configuration_options={
      bossres=true,
      companion=true,
      dist=2.5,
      language="CHS",
      minimapicon=false,
      ownership=0,
      rebounddmg=500,
      recipe="normal",
      recipe_door=true,
      recipe_fence=true,
      recipe_tool=true,
      recipe_vanilla=false,
      recipe_wall=true 
    },
    enabled=true 
  },
  ["workshop-786556008"]={
    configuration_options={ ENABLEBACKPACK=true, EXTRASLOT=0, INVENTORYSIZE=45 },
    enabled=true 
  },
  ["workshop-791838548"]={
    configuration_options={
      Dispenser_Difficulty="default",
      EHat_Difficulty="default",
      Scrap_Difficulty="default",
      Sentry_Damage=9.5,
      Sentry_Difficulty="default",
      Sentry_Health=200,
      Sentry_ROF=1,
      Sentry_Range=13,
      Teleporter_Difficulty="default",
      dispenserhealingrate=3,
      disprange=2,
      ehardhatdura=295,
      engiedmgdebuff=0.8,
      hardhatabsorb=0.7,
      rocketsplashdmg="y",
      sentryh_regen="n",
      tf2Wrench_Difficulty="default",
      tf2wrenchdmg=17,
      tf2wrenchuses=150 
    },
    enabled=true 
  } 
}