name: sync file
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: sync hexo file to blog
    steps:
    - name: Setup Deploy Private Key
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Setup Git Infomation
      run: | 
        git config --global user.name 'github-actions[bot]' 
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - name: Clone File
      run: |
        git clone https://github.com/inkss/Hexo-Blog.git Hexo-Blog
        git clone https://github.com/inkss/markdown.git markdown
        cp -f markdown/Hexo/* Hexo-Blog/source
    - name: Sync File
      run: |
        cd Hexo-Blog
        git add .
        git commit -m 'sync file'
        git push -f
